export const PERMISSIONS = {
  COMPANY_READ: 'company:read',
  COMPANY_UPDATE: 'company:update',
  TENANT_READ: 'tenant:read',
  TENANT_UPDATE: 'tenant:update',
  USER_CREATE: 'user:create',
  USER_INVITE: 'user:invite',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  RBAC_MANAGE: 'rbac:manage',
  JOB_CREATE: 'job:create',
  JOB_READ: 'job:read',
  JOB_UPDATE: 'job:update',
  CANDIDATE_CREATE: 'candidate:create',
  CANDIDATE_READ: 'candidate:read',
  CANDIDATE_UPDATE: 'candidate:update',
  PIPELINE_CREATE: 'pipeline:create',
  PIPELINE_READ: 'pipeline:read',
  PIPELINE_UPDATE: 'pipeline:update',
  EVALUATION_CREATE: 'evaluation:create',
  EVALUATION_READ: 'evaluation:read',
  EVALUATION_UPDATE: 'evaluation:update',
  COMMUNICATION_CREATE: 'communication:create',
  COMMUNICATION_READ: 'communication:read',
  ANALYTICS_CREATE: 'analytics:create',
  ANALYTICS_READ: 'analytics:read',
  AUDIT_CREATE: 'audit:create',
  AUDIT_READ: 'audit:read',
  LINKEDIN_CONNECT: 'linkedin:connect',
  LINKEDIN_POST: 'linkedin:post',
  LINKEDIN_READ: 'linkedin:read',
} as const;

export type PermissionValue = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
